theme: jekyll-theme-minimal
title: Konstantinos D. Gidarakos
description: ©2022 Konstantinos D. Gidarakos - Computer Systems Engineer
logo: https://3.bp.blogspot.com/-y2uo1sdvWmY/Ts-ibB5l-bI/AAAAAAAATDI/515LjaTZB6g/s1600/Ubuntu-12.04-Precise-Pangolin-Features.jpg
show_downloads: false
