remote_theme: 
title: Konstantinos D. Gidarakos
description: ©2021 Konstantinos D. Gidarakos - Computer Systems Engineer
logo: https://3.bp.blogspot.com/-y2uo1sdvWmY/Ts-ibB5l-bI/AAAAAAAATDI/515LjaTZB6g/s1600/Ubuntu-12.04-Precise-Pangolin-Features.jpg
